### ISSUE TITLE
REST API to execute bash scripts

### ISSUE THREAD

**Issue by Nexuist** [sorenisanerd/gotty#11]
Use case: I have a lot of scripts hanging around that glue two services together, ingest data into a database, scrape a page, etc. Usually if I want more interactivity I have to port the script to a Web server and HTML forms.

It would be great if I could instead assign a script to a URL, so that I could send a POST or GET request to a gotty URL and spawn a process with URL parameters being ported to command line arguments. This could then redirect to an ephemeral URL for the specific process, so if it takes a long time I can come back to the URL to see what the script is doing. Additionally, if the script prompts for user input, the process could just hang until I visit the URL again to type in input. This way I can periodically check in on my scripts without having to use `ssh` and `screen`, and automate their execution using tools like `curl` or `wget`.

**Comment by sorenisanerd** [comment]
I'm not sure I follow completely.

If you're looking for a simple way to execute commands in response to an HTTP request, I recommend you look at https://github.com/msoap/shell2http. If anything executed there is interactive, you could run it under screen and, if need be, you could connect to it using gotty ("`gotty -w screen -r -d -S sessionname`").

Without screen in the mix, I'm not sure how `curl` / `wget` would be used to trigger these commands.

**Comment by Nexuist** [comment]
Thanks for the link, I will check it out.
