### ISSUE TITLE
WebGL rendering broken in Safari (14.1)

### ISSUE THREAD

**Issue by prusnak** [sorenisanerd/gotty#15]
### What version of GoTTY are you using (`gotty --version`)?

1.3.0

### What operating system and browser are you using?

macOS 11.3 on Apple Silicon
Safari 14.1

### What did you do?

Just run gotty with any command. Safari does not show any characters, just the background color.

### What did you expect to see?

Normal font rendering

----

Running `GOTTY_ENABLE_WEBGL=0 gotty top` fixes the issue.

It seems that WebGL is enabled by default despite the documentation says WebGL is disabled by default. I am opening second issue for this - https://github.com/sorenisanerd/gotty/issues/16

**Comment by sorenisanerd** [comment]
I don't have access to a system like that, so I can't reproduce it. Is there any chance you could find a similar system and see if it's reproducible?

According to https://openbase.com/js/xterm-addon-webgl/documentation:

> Since xterm.js is typically implemented as a developer tool, only modern browsers are supported officially. Specifically the latest versions of Chrome, Edge, Firefox, and Safari.

....so it should work.

**Comment by prusnak** [comment]
It was caused by experimental WebGL 2.0 enabled in Safari - https://github.com/xtermjs/xterm.js/issues/3357#issuecomment-852907822

Closing
