### ISSUE TITLE
HTTP headers processing

### ISSUE THREAD

**Issue by George-NG** [sorenisanerd/gotty#23]
Not a bug report, just wanted to share this code change without creating a pull request as this is potentially unsafe change to add to the code base.

https://github.com/sorenisanerd/gotty/compare/master...George-NG:process-http-headers

(the specific branch is https://github.com/George-NG/gotty/tree/process-http-headers )

This would pass headers from the browser and any proxy servers (ie nginx) to the backend application in the form of env vars prefixed with `HTTP_`.

I am using this for a non-publicly accessible project, where we need some headers to be sent to the backend. I have not checked about security implications at all and there is possibly a better way to do this, ie not at the time of creating the websocket and for each and every request. Since currently there is no option in the project (or I couldn't find one!) to pass headers to the backend, I thought I might share this anyway for anyone who might need something similar.

Any feedback is appreciated, as I am going to use this for the foreseeable future and don't want to leave an obvious wide open security gap in place :sweat_smile:

For anyone who thinks of using this at its current state, be very careful about what you are processing and sanitize input as much as possible via a proxy in front of gotty.

**Comment by sorenisanerd** [comment]
There's an option (--permit-arguments) to pass arguments to the command being invoked. When enabled, you can do: http://example.com:8080/?arg=AAA&arg=BBB and your command will receive "AAA" and "BBB" as its arguments.

Will that work for you?

**Comment by George-NG** [comment]
Hi Soren,

Yes, using the `--permit-arguments` option could work in some cases.

What I am using gotty for is essentially a (F)CGI server, to be able to transition a terminal-only project to the web. Because of that, I need gotty to be able to forward HTTP headers to the backend, so the development work can continue till it reaches the point where the project will be moved to its own application server.

I have other projects in the pipeline that will be "webified" without really needing anything more than just be available on the corporate lan, that may actually use the arguments, ie where we just need a common subset of http headers, like referer, user-agent and host. However adding more headers later on means modifications to the source and/or configuration of the software running before and after gotty. So for me it made much more sense to make this small change in gotty and have the functionality across projects.

**Comment by sorenisanerd** [comment]
That makes sense. Can you add an option to enable it (it should be disabled by default) and send a PR?

**Comment by George-NG** [comment]
Apologies, live has been hectic and I wasn't able to look at this till now. Looks like Lukasz already added the option, so that should be fine. I'll close this issue.
