### ISSUE TITLE
我怎么获取随机数，我可以自定义随机数吗？

### ISSUE THREAD

**Issue by qigj** [sorenisanerd/gotty#24]
# When file a bug report (see below for feature requests)

Please answer these quesions for a bug report. Thanks!

### What version of GoTTY are you using (`gotty --version`)?
gotty version v1.3.0

### What did you do?

If possible, please provide the command you ran.

### What did you see instead?

If possible, please provide the output of the command and your browser's console output.

# When file a new feature proposal

Please provide an actual usecase that requires your new feature.

**Comment by sorenisanerd** [comment]
Can you explain what you're trying to do?

**Comment by sorenisanerd** [comment]
Closing as it's not clear what the problem is.
