### ISSUE TITLE
-m 404

### ISSUE THREAD

**Issue by Fan-SJ** [sorenisanerd/gotty#29]
# When file a bug report (see below for feature requests)

Please answer these quesions for a bug report. Thanks!

### What version of GoTTY are you using (`gotty --version`)?
gotty version v1.3.0

### What operating system and browser are you using?
MAC OS
chrome

### What did you do?

./gotty --path /t df -h

### What did you see instead?

<img width="672" alt="image" src="https://user-images.githubusercontent.com/49977708/153175681-e439990e-3feb-4d27-aff3-b4d1056056cd.png">

# When file a new feature proposal

Please provide an actual usecase that requires your new feature.

**Comment by mcguirepr89** [comment]
Hello -- thank you, @sorenisanerd for maintaining this. I have had an issue getting the "`--path`" global option to function properly.

My GoTTY version is:`gotty version v1.4.0`
OS: RaspiOS-Lite AArch64
Browser: Chrome (version `Google Chrome 104.0.5112.101`)


What I did:
```
./gotty --address 0.0.0.0 --port 8000 --path /a ls
```

Terminal output:
```
raspberrypi ➜  ~ ./gotty --address 0.0.0.0 --port 8000 --path '/a' ls       
2022/08/19 15:42:47 GoTTY is starting with command: ls
2022/08/19 15:42:47 HTTP server is listening at: http://[::]:8000/a
2022/08/19 15:42:47 Alternative URL: http://127.0.0.1:8000/a
2022/08/19 15:42:47 Alternative URL: http://[::1]:8000/a
2022/08/19 15:42:47 Alternative URL: http://192.168.1.192:8000/a
2022/08/19 15:42:47 Alternative URL: http://[2600:4040:264f:7600:e20b:7d8f:90e7:e314]:8000/a
2022/08/19 15:42:47 Alternative URL: http://[fe80::c636:bd47:82c4:419a]:8000/a
2022/08/19 15:42:53 192.168.1.188:38110 200 GET /a
2022/08/19 15:42:53 192.168.1.188:38110 404 GET /css/index.css
2022/08/19 15:42:53 192.168.1.188:38126 404 GET /css/xterm.css
2022/08/19 15:42:53 192.168.1.188:38110 404 GET /css/xterm_customize.css
2022/08/19 15:42:53 192.168.1.188:38130 404 GET /auth_token.js
2022/08/19 15:42:53 192.168.1.188:38134 404 GET /config.js
2022/08/19 15:42:53 192.168.1.188:38150 404 GET /js/gotty.js
```

And the GoTTY web page is blank white:
![Screenshot from 2022-08-19 15-43-37](https://user-images.githubusercontent.com/60325264/185695531-44568f71-8327-4dfa-8dca-31c0bd807489.png)


I will be very grateful for any help with this.
My very best regards,
Patrick

**Comment by xgdgsc** [comment]
From some code digging, I found you need the backslashes both at begin and end of the path, like `/a/`

**Comment by sorenisanerd** [comment]
As @xgdgsc says, you can work around this by adding a trailing slash to the path. The next version of GoTTY will do this automatically, thanks to a patch from @xgdgsc :)
