### ISSUE TITLE
[Feature Request] static binary to run in alpine container

### ISSUE THREAD

**Issue by shuaiyy** [sorenisanerd/gotty#39]
# When file a bug report (see below for feature requests)

when run gotty in alpine docker container, got the error: 

./bin/gotty 
sh: ./bin/gotty: not found

### What version of GoTTY are you using (`gotty --version`)?
1.4.0

### What did you do?

docker run -it --entrypoint sh --rm alpine:3.11

# When file a new feature proposal

in some minimal docker image like alpine/ busybox, c lib may not installed.

**Comment by sorenisanerd** [comment]
Good catch! Thanks!  This is fixed in the development builds now.
