### ISSUE TITLE
How to debug the front-end code locally ？

### ISSUE THREAD

**Issue by Yann-Qiu** [sorenisanerd/gotty#40]
Hello.

I am currently using your repository for local development. It really works very well and I appreciate it.
But at the moment I have a question, how do you debug the front-end code locally (especially js part as well as html etc) By building a separate http server, which is possible. But I don't know if it is already supported inside your code?

I would be grateful if I could get an answer from you.

**Comment by sorenisanerd** [comment]
I rely a lot on Chrome's devtools. Under the `Sources` tab you can find the typescript files and set breakpoints and everything.

**Comment by sorenisanerd** [comment]
https://github.com/sorenisanerd/gotty/wiki/Developing-GoTTY
