### ISSUE TITLE
node v18.10.0 | webpack --mode=production: --: not found

### ISSUE THREAD

**Issue by v20z** [sorenisanerd/gotty#52]
Hello Soren.

Got issue compiling with several last node vesions:
```
cd js && \
npm install

added 249 packages, and audited 250 packages in 3s

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
cd js && \
npx webpack --mode=production
webpack --mode=production: --: not found
make: *** [Makefile:45: bindata/static/js/gotty.js.map] Error 127
```
With lower node v187.0 compilation passed allright.

Which side is erroneus?

**Comment by sorenisanerd** [comment]
I cannot reproduce this problem with the latest Node 18.11.0. Which exact version of Node are you using?

**Comment by v20z** [comment]
Hello Soren.

Yes, I'm sorry. That was false alarm. After you have specified  I've updated `node` to 8.11.0 from source and cleared `go` packages cache. After that `gotty`  git downloaded and compiled smoothly. I was misled by successful build of all previous versions on a different server.

Thank you for your work and attention.

**Comment by sorenisanerd** [comment]
Sure thing. Thanks for taking the time to report the problem.
