### ISSUE TITLE
What's new in this fork?

### ISSUE THREAD

**Issue by jpillora** [sorenisanerd/gotty#8]
What do I get from this version over the original version?

P.s. Although the license doesn't require you to, you should still credit http://github.com/yudai/gotty since this repo isn't a linked fork

**Comment by sorenisanerd** [comment]
For one thing, it is actually maintained. I'm happy to accept patches or work on issues, etc.

@yudai's work on this project is fantastic and I'm more than happy to give him the credit that is due. He's listed first in the list of contributors. Is there somewhere in particular where you feel he's not given sufficient credit?

**Comment by jpillora** [comment]
Okay so its mostly a repo for bug fixes? oh it's continuing @yudai's unreleased alpha v2?

Maybe a credit section in the README with a link back to source repo?

**Comment by sorenisanerd** [comment]
Not just bug fixes, definitely also new features. File transfers and SPiCE integration are both in the works.

I'll add a more prominent reference to @yudai :)

**Comment by jpillora** [comment]
Awesome 👍
