### ISSUE TITLE
Add support for customizing the url used for interacting with websocket

### ISSUE THREAD

**Issue by josegonzalez** [sorenisanerd/gotty#82]
I have a golang service that proxies to gotty. It provides authentication via an ephemeral token in a query parameter as described [here](https://ably.com/blog/websocket-authentication#send-an-ephemeral-access-token-in-the-query-parameter). The service doesn't use HTTPS cookies for authentication, and using the built-in basic auth support for authenticating via credentials would be extra overhead due to  already being logged into the system.

In the ideal case, I could specify a custom set of query string parameters - perhaps via some sort of `config.js` `var gotty_query_string` like [here](https://github.com/sorenisanerd/gotty/blob/113b502abbbb273530b6bdbeec5b3b741d712d14/server/handlers.go#L228-L237) - that could be included in the query [here](https://github.com/sorenisanerd/gotty/blob/master/js/src/main.ts#L16) and then added [here](https://github.com/sorenisanerd/gotty/blob/113b502abbbb273530b6bdbeec5b3b741d712d14/js/src/main.ts#L16) to the open of each websocket. This would provide allow my proxy service the ability to handle authentication as is without needing to implement workarounds.

Would you be willing to accept a PR that implemented this?

**Comment by sorenisanerd** [comment]
Sure, sounds perfectly reasonable :)

**Comment by josegonzalez** [comment]
@sorenisanerd I made a couple of PRs. If you have a chance in the near future, would be great to get some 👀 on them. Happy to make changes as well!

**Comment by josegonzalez** [comment]
@sorenisanerd friendly _bump_ :)

**Comment by Gigko** [comment]
--ws-query-args
how can i use that to connect from separate xtermjs ?
